### PR TITLE
don't check resp.* when error occurs

### PR DESCRIPTION
**Pull request by bitbytebit-cr**
Jira: VOD-4248

folow-up fix from error seen in logs. doesn't break behavior for
client, yet fails to log the error, would exit anyways and error
with an HTTP 500 (which happens anyways).

Exact spot in code: https://onenr.io/0ERPpMomDRW
Overall log messages view: https://onenr.io/0dQeVZYrawe

### CODE REVIEW

**Comment by mlevkov** [comment]
@bitbytebit-cr please don't use Sprintf in this code base, see this -> https://gist.github.com/dtjm/c6ebc86abe7515c988ec. Try to pick a solution the most performant solution that works.  Also, an empty return from a function results in `nil` even though it is used as an early return.

**Comment by bitbytebit-cr** [comment]
> @bitbytebit-cr please don't use Sprintf in this code base, see this -> https://gist.github.com/dtjm/c6ebc86abe7515c988ec. Try to pick a solution the most performant solution that works. 

It has non string stuff to concatenate too, this is just for strings in the example, we have to use Sprintf and it is not non-performant. This is quibbling for the nanoseconds which is tiny in cost and only for the strings so seems rather negligible when seeing it can't cover the most largest Sprintf tasks of structures etc in in Go to print out into string form.

>Also, an empty return from a function results in `nil` even though it is used as an early return.

Yes It had been expecting the response to contain a status code from S3, which can't happen in this error return case (these are timeout's mostly it seems, cases where nothing was gotten back from S3).

**Review by dchamberlin-cr — APPROVED** [review]
This look good to me.

**Review by rmikhael — APPROVED** [review]
I would vote to not worry about Premature Optimization yet. With a compiler, we cannot generalize results from one test-case to another. The tests quoted were printing an array of strings, which might be different from a structure of non-strings...etc. Wouldn't believe it till we run our own load testing for the code we want to compare.
Second, when it comes to performance, we have a lot more ideas on how to optimize this and spare CPU that would pay more than replacing the Sprintf.
Third point, this PR is about REMOVING one Sprintf, so discussion of other pieces should go in parallel, but not block this PR.

**Comment by bitbytebit-cr** [comment]
> @bitbytebit-cr please don't use Sprintf in this code base, see this -> https://gist.github.com/dtjm/c6ebc86abe7515c988ec. Try to pick a solution the most performant solution that works. Also, an empty return from a function results in `nil` even though it is used as an early return.

I created VOD-4303 to follow up with optimizations like the above suggestion. Thank you! Please consider approving this bug fix for now.

**Review by mlevkov — APPROVED** [review]

**Pull request merged**
