### PR TITLE
Mort 1658 #3b

### PR DESCRIPTION
**Pull request by bitbytebit-cr**
Jira: MORT-1658

revert only AWS SDK S3 getObject() usage.

### CODE REVIEW

**Comment by bitbytebit-cr** [comment]
This has one issue, that the return code now is accurate to S3 return status (404 when media is missing). Yet the QA Testrail tests look for 502 since previously that was the hardcoded return value when content was missing it seems. I am confirming this, but may need tests to be fixed to accurately use 404 as expected results for this to run through jenkins tests. Else I could still fudge but the point was to get status codes returned accurately. Oddly the AWS SDK getObject method wasn't doing that, and now the combined changes without that method (using http signing instead) gets the right error code.

I believe the getObject() requests are the problem with the ram memory running out. That is my theory with this attempt.

**Review by rmikhael — APPROVED** [review]
+1

**Review by mlevkov — APPROVED** [review]

**Review by rmikhael — DISMISSED** [review]
+1

**Review by rmikhael — DISMISSED** [review]
+1

**Review by mlevkov — APPROVED** [review]

**Review by mlevkov — APPROVED** [review]

**Review by mlevkov — APPROVED** [review]

**Review by rmikhael — APPROVED** [review]

**Pull request merged**
